name: Sync GitHub to GitLab

on:
  push:
    branches:
      - main
      - dev
      - qa
      - uat

jobs:
  sync:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch: [main, dev, qa, uat]

    steps:
      # Step 1: Checkout GitHub repository
      - name: Checkout GitHub Repository
        uses: actions/checkout@v2

      # Step 2: Setup SSH for GitLab
      - name: Setup SSH for GitLab
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITLAB_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H gitlab.presidio.com >> ~/.ssh/known_hosts

      # Step 3: Add GitLab remote
      - name: Add GitLab remote
        run: git remote add gitlab git@gitlab.presidio.com:jarvis-hai/hai-vscode-plugin.git

      # Step 4: Fetch GitLab branch
      - name: Fetch GitLab branch
        run: git fetch gitlab ${{ matrix.branch }} || true

      # Step 5: Merge changes
      - name: Merge changes
        run: |
          git checkout -b ${{ matrix.branch }} gitlab/${{ matrix.branch }} || git checkout ${{ matrix.branch }}
          git pull gitlab ${{ matrix.branch }} || true
          git merge --no-ff ${{ matrix.branch }} || true

      # Step 6: Push changes to GitLab
      - name: Push changes
        run: git push gitlab ${{ matrix.branch }}
